# Generated by Django 4.1.3 on 2022-11-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
