# Generated by Django 4.1.3 on 2022-11-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_customer_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
