# Generated by Django 4.1 on 2022-11-09 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_bike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike", name="uuid", field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
